springdoc.version=v1
app.api.version=v1
app.api.base=/api/${app.api.version}
app.api.swagger.title=CooperAgro uma plataforma para agricultores familiares
app.api.swagger.base-package=com.cooperagro.backend
app.api.security.url-auth-controller=/api/${app.api.version}/auth
#app.api.security.jwt.token-expire-in=3600
#app.api.security.jwt.token-refresh-in=3600

server.port=8081
spring.datasource.url=jdbc:mariadb://localhost:3306/cooperagro
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop

#para mostrar SQL
spring.jpa.properties.hibernate.format_sql=true
#para mostrar os parametros da sql
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
# Set to enable hot deployment
spring.devtools.restart.enabled=true
# restart directory
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.exclude: WEB-INF/**


server.error.include-message=always
server.error.include-stacktrace=never

spring.messages.basename=messages,messages-arquitetura

#DOCKER
#docker run -p 3306:3306 --name cooperagro -e MYSQL_ROOT_PASSWORD=root -d mariadb