springdoc.version=v1
app.api.version=v1
app.api.base=/api/${app.api.version}
app.api.swagger.title=CooperAgro uma plataforma para agricultores familiares
app.api.swagger.base-package=com.cooperagro.cooperagro

server.port=8081
spring.datasource.url=jdbc:mariadb://localhost:3306/cooperagro
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

#DOCKER
#docker run -p 3306:3306 --name cooperagro -e MYSQL_ROOT_PASSWORD=root -d mariadb